// THIS FILE IS AUTOGENERATED
// DO NOT EDIT THIS FILE!

import "@algolia/autocomplete-theme-classic";
import "./index.css";
import lunr from "lunr";

require("lunr-languages/lunr.stemmer.support")(lunr);
require("lunr-languages/lunr.zh")(lunr);
export const tokenize = (input) =>
  input
    .trim()
    .toLowerCase()
    .split(/[\s\-]+/)
    .filter((each) => !!each);
export const mylunr = lunr;
