// @ts-ignore
import { NoHydration, HydrationScript, renderToStringAsync } from "solid-js/web";
import { extractCss } from "goober";
import App from "./App";
export async function render(url: string, manifest: any, pipe?: boolean) {
  // if (pipe) {
  const html = await renderToStringAsync(() => <App />);
  const preloadLinks = await renderToStringAsync(() => (
    <>
      {/* <style innerText={css}></style> */}
      <NoHydration>
        <style id="_goober">{extractCss()}</style>
        <link as="style" rel="preload" href="/src/assets/index.css"></link>
      </NoHydration>
      <HydrationScript />
    </>
  ));
  //   return [html, preloadLinks];
  // }

  // the SSR manifest generated by Vite contains module -> chunk/asset mapping
  // which we can then use to determine what files need to be preloaded for this
  // request.
  return (template: string, res: any) => {
    res
      .status(200)
      .set({ "Content-Type": "text/html" })
      .end(
        template.replace(`<!--preload-links-->`, preloadLinks).replace(`<!--ssr-outlet-->`, html)
      );
    // pipeToNodeWritable(() => <HTML />, res, {
    //   onComplete(res) {
    //     res.write(html);
    //   },
    // });
  };
}
