import {
  AstNode,
  createDefaultModule,
  DefaultJsonSerializer,
  DefaultModuleContext,
  inject,
  LangiumServices,
  Module,
  PartialLangiumServices,
} from "langium";
import { AstNodeDescriptionProvider, AstNodeLocator } from "./advscript-provider";
import { AdvscriptValidationRegistry, AdvscriptValidator } from "./advscript-validator";
import { AdvscriptAstReflection, reflection } from "./ast";
import { createCustomParser, CustomParser } from "./CustomParser";
import { CustomTokenBuilder } from "./customTokens";
// import { OhmParser } from "./custom";
import { AdvscriptGeneratedModule } from "./generated/module";
import * as Lsp from "./lsp";
import * as References from "./references";

/**
 * Declaration of custom services - add your own service classes here.
 */
export type AdvscriptAddedServices = {
  AstReflection: AdvscriptAstReflection;
  validation: {
    AdvscriptValidator: AdvscriptValidator;
  };
  parser: {
    TokenBuilder: CustomTokenBuilder;
    LangiumParser: CustomParser;
  };
  references: References.Providers;
  lsp: Lsp.Providers;
};

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type AdvscriptServices = LangiumServices & AdvscriptAddedServices;

class JsonSerializer extends DefaultJsonSerializer {
  serialize(node: AstNode, space?: string | number): string {
    try {
      return super.serialize(node, space);
    } catch (error) {
      return "<node:" + node.$type + ">";
    }
  }
}
/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const AdvscriptModule: Module<
  AdvscriptServices,
  PartialLangiumServices & AdvscriptAddedServices
> = {
  AstReflection: () => reflection,
  validation: {
    ValidationRegistry: (injector) => new AdvscriptValidationRegistry(injector),
    AdvscriptValidator: (injector) => new AdvscriptValidator(injector),
  },
  references: {
    Linker: (injector) => new References.Linker(injector),
    ScopeComputation: (injector) => new References.ScopeComputation(injector),
    NameProvider: (injector) => new References.NameProvider(injector),
    ScopeProvider: (i) => new References.ScopeProvider(i),
    References: (s) => new References.References(s),
  },
  index: {
    AstNodeLocator: () => new AstNodeLocator(),
    AstNodeDescriptionProvider: (injector) => new AstNodeDescriptionProvider(injector),
  },
  serializer: {
    JsonSerializer: (i) => new JsonSerializer(i),
  },
  // parser: {
  //     LangiumParser: (service) => new OhmParser(service) as any,
  // },
  parser: {
    TokenBuilder: () => new CustomTokenBuilder(),
    LangiumParser: (services) => createCustomParser(services) as never,
  },
  lsp: {
    HoverProvider: (service) => new Lsp.HoverProvider(service),
    CodeActionProvider: (service) => new Lsp.CodeActionProvider(service),
    DocumentSemanticProvider: (service) => new Lsp.DocumentSemanticProvider(service),
    ReferenceFinder: (services) => new Lsp.ReferenceFinder(services),
    RenameHandler: (services) => new Lsp.RenameHandler(services),
    DocumentSymbolProvider: (services) => new Lsp.DocumentSymbolProvider(services),
    completion: {
      CompletionProvider: (services) => new Lsp.CompletionProvider(services),
    },
  },
};
/**
 * Inject the full set of language services by merging three modules:
 *  - Langium default services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 */
export function createAdvscriptServices(context?: DefaultModuleContext): AdvscriptServices {
  return inject(createDefaultModule(context), AdvscriptGeneratedModule, AdvscriptModule);
}
