import {
  AstNode,
  createDefaultSharedModule,
  DefaultJsonSerializer,
  inject,
  LangiumParser,
  LangiumServices,
  Module,
  PartialLangiumServices,
  DefaultSharedModuleContext,
  createDefaultModule,
  DeepPartial,
  LangiumSharedServices,
  LangiumDocument
} from "langium";
import { URI } from "vscode-uri";
import { AstNodeDescriptionProvider, AstNodeLocator } from "./advscript-provider";
import { AdvscriptValidationRegistry, AdvscriptValidator } from "./advscript-validator";
import { AvsAstReflection, astReflection } from "./ast-utils";
import { createCustomParser, CustomParser } from "./CustomParser";
import { CustomTokenBuilder } from "./customTokens";
import { AdvscriptGeneratedModule, AdvScriptGeneratedSharedModule } from "./generated/module";
import * as Lsp from "./lsp";
import * as References from "./references";

type WrapperLangiumParser<T> = LangiumParser & Omit<T, "">;

/**
 * Declaration of custom services - add your own service classes here.
 */
export interface AdvscriptAddedServices {
  shared?: {
    AstReflection: AvsAstReflection;
  };
  validation: {
    AdvscriptValidator: AdvscriptValidator;
  };
  parser: {
    TokenBuilder: CustomTokenBuilder;
    LangiumParser: WrapperLangiumParser<CustomParser>;
  };
  references: References.Providers;
  lsp: Lsp.Providers;
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type AdvScriptServices = LangiumServices & AdvscriptAddedServices;

class JsonSerializer extends DefaultJsonSerializer {
  serialize(node: AstNode, space?: string | number): string {
    try {
      return super.serialize(node, space);
    } catch (error) {
      return "<node:" + node.$type + ">";
    }
  }
}
/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const AdvscriptModule: Module<
  AdvScriptServices,
  PartialLangiumServices & AdvscriptAddedServices
> = {
  validation: {
    ValidationRegistry: (injector) => new AdvscriptValidationRegistry(injector),
    AdvscriptValidator: (injector) => new AdvscriptValidator(injector)
  },
  references: {
    Linker: (injector) => new References.Linker(injector),
    ScopeComputation: (injector) => new References.ScopeComputation(injector),
    NameProvider: (injector) => new References.NameProvider(injector),
    ScopeProvider: (injector) => new References.ScopeProvider(injector),
    References: (injector) => new References.References(injector)
  },
  index: {
    AstNodeLocator: () => new AstNodeLocator(),
    AstNodeDescriptionProvider: (injector) => new AstNodeDescriptionProvider(injector)
  },
  // serializer: {
  //   JsonSerializer: (injector) => new JsonSerializer(injector)
  // },
  // parser: {
  //     LangiumParser: (service) => new OhmParser(service) as any,
  // },
  parser: {
    TokenBuilder: () => new CustomTokenBuilder(),
    LangiumParser: (services) =>
      createCustomParser(services) as unknown as WrapperLangiumParser<CustomParser>
  },
  lsp: {
    HoverProvider: (service) => new Lsp.HoverProvider(service),
    CodeActionProvider: (service) => new Lsp.CodeActionProvider(service),
    DocumentSemanticProvider: (service) => new Lsp.DocumentSemanticProvider(service),
    ReferenceFinder: (services) => new Lsp.ReferenceFinder(services),
    RenameHandler: (services) => new Lsp.RenameHandler(services),
    DocumentSymbolProvider: (services) => new Lsp.DocumentSymbolProvider(services),
    DocumentHighlighter: (services) => new Lsp.DocumentHighlighter(services),
    DocumentFormattingEdits: (services) => new Lsp.DocumentFormattingEdits(services),
    completion: {
      CompletionProvider: (services) => new Lsp.CompletionProvider(services),
      RuleInterpreter: (services) => new Lsp.RuleInterpreter(services)
    }
  }
};
/**
 * Inject the full set of language services by merging three modules:
 *  - Langium default services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 */
export function createAdvscriptServices(context?: DefaultSharedModuleContext): {
  shared: LangiumSharedServices;
  advscript: AdvScriptServices;
} {
  const shared = inject(createDefaultSharedModule(context), {
    ...AdvScriptGeneratedSharedModule,
    AstReflection: () => astReflection
  });
  const advscript = inject(
    createDefaultModule({ shared }),
    AdvscriptGeneratedModule,
    AdvscriptModule
  );
  shared.ServiceRegistry.register(advscript);
  return { shared, advscript };
}

export function createBrowerServices<T extends DeepPartial<LangiumSharedServices>>(
  module?: Module<LangiumSharedServices, T>,
  context?: DefaultSharedModuleContext
) {
  const shared = inject(createDefaultSharedModule(context), {
    ...AdvScriptGeneratedSharedModule,
    AstReflection: () => astReflection,
    ...module
  });
  const advscript: AdvScriptServices = inject(
    createDefaultModule({ shared }),
    AdvscriptGeneratedModule,
    AdvscriptModule
  );
  shared.ServiceRegistry.register(advscript);
  return { shared, advscript };
}

export * as ast from "./ast";

import { FileSystemNode, FileSystemProvider } from "langium/lib/workspace/file-system-provider";

export class BrowerFileReader implements FileSystemProvider {
  static store = new Map<string, string>();

  static writeStore(path: string, content: string) {
    this.store.set(URI.parse(path).path, content);
  }

  static getOrCreateDocument<Node extends AstNode>(share: LangiumSharedServices, path: string) {
    return share.workspace.LangiumDocuments.getOrCreateDocument(
      URI.file(path)
    ) as LangiumDocument<Node>;
  }

  async readFile(uri: URI): Promise<string> {
    return BrowerFileReader.store.get(uri.path);
  }

  readFileSync(uri: URI): string {
    // console.log("readFileSync", uri)
    return BrowerFileReader.store.get(uri.path);
  }

  async readDirectory(folderPath: URI): Promise<FileSystemNode[]> {
    return [];
  }
}
