export const eventHandlers = [
  "ready",
  "click",
  "mousedown",
  "mousemove",
  "mouseout",
  "mouseover",
  "mouseup",
  "mouseupoutside",
  "tap",
  "touchstart",
  "touchmove",
  "touchend",
  "touchendoutside",
  "pointercancel",
  "pointerout",
  "pointerover",
  "pointertap",
  "pointerdown",
  "pointerup",
  "pointerupoutside",
  "pointermove",
  "rightclick",
  "rightdown",
  "rightup",
  "rightupoutside",
  "touchcancel",
  "touchendoutside",
  "touchmove",
  "touchstart",
] as const;

export type EventHandlers = typeof eventHandlers[number];
export const EventHandlers = eventHandlers as unknown as EventHandlers[];
