import ts, { factory } from "typescript";
export const testModule = ts.factory.createSourceFile(
  [
    factory.createImportDeclaration(
      undefined,
      undefined,
      factory.createImportClause(
        false,
        undefined,
        factory.createNamedImports([
          factory.createImportSpecifier(false, undefined, factory.createIdentifier("map")),
        ])
      ),
      factory.createStringLiteral("lodash")
    ),
    factory.createFunctionDeclaration(
      undefined,
      [factory.createModifier(ts.SyntaxKind.ExportKeyword)],
      undefined,
      factory.createIdentifier("test"),
      undefined,
      [],
      undefined,
      factory.createBlock(
        [
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("value"),
                  undefined,
                  undefined,
                  factory.createNumericLiteral("0")
                ),
                factory.createVariableDeclaration(
                  factory.createIdentifier("target"),
                  undefined,
                  undefined,
                  factory.createObjectLiteralExpression([], false)
                ),
              ],
              ts.NodeFlags.Let
            )
          ),
          factory.createVariableStatement(
            undefined,
            factory.createVariableDeclarationList(
              [
                factory.createVariableDeclaration(
                  factory.createIdentifier("result"),
                  undefined,
                  undefined,
                  factory.createCallExpression(factory.createIdentifier("map"), undefined, [
                    factory.createArrayLiteralExpression(
                      [
                        factory.createNumericLiteral("1"),
                        factory.createNumericLiteral("2"),
                        factory.createNumericLiteral("3"),
                        factory.createNumericLiteral("4"),
                        factory.createNumericLiteral("5"),
                      ],
                      false
                    ),
                    factory.createArrowFunction(
                      undefined,
                      undefined,
                      [
                        factory.createParameterDeclaration(
                          undefined,
                          undefined,
                          undefined,
                          factory.createIdentifier("i"),
                          undefined,
                          undefined,
                          undefined
                        ),
                        factory.createParameterDeclaration(
                          undefined,
                          undefined,
                          undefined,
                          factory.createIdentifier("index"),
                          undefined,
                          undefined,
                          undefined
                        ),
                        factory.createParameterDeclaration(
                          undefined,
                          undefined,
                          undefined,
                          factory.createIdentifier("arr"),
                          undefined,
                          undefined,
                          undefined
                        ),
                      ],
                      undefined,
                      factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                      factory.createBlock(
                        [
                          factory.createVariableStatement(
                            undefined,
                            factory.createVariableDeclarationList(
                              [
                                factory.createVariableDeclaration(
                                  factory.createObjectBindingPattern([
                                    factory.createBindingElement(
                                      undefined,
                                      factory.createIdentifier("value"),
                                      factory.createIdentifier("value2"),
                                      undefined
                                    ),
                                    factory.createBindingElement(
                                      undefined,
                                      factory.createIdentifier("v"),
                                      factory.createObjectBindingPattern([
                                        factory.createBindingElement(
                                          undefined,
                                          factory.createIdentifier("result"),
                                          factory.createIdentifier("result1"),
                                          undefined
                                        ),
                                      ]),
                                      undefined
                                    ),
                                  ]),
                                  undefined,
                                  undefined,
                                  factory.createObjectLiteralExpression(
                                    [
                                      factory.createShorthandPropertyAssignment(
                                        factory.createIdentifier("value"),
                                        undefined
                                      ),
                                      factory.createPropertyAssignment(
                                        factory.createIdentifier("v"),
                                        factory.createObjectLiteralExpression(
                                          [
                                            factory.createShorthandPropertyAssignment(
                                              factory.createIdentifier("result"),
                                              undefined
                                            ),
                                          ],
                                          false
                                        )
                                      ),
                                    ],
                                    false
                                  )
                                ),
                              ],
                              ts.NodeFlags.Let
                            )
                          ),
                          factory.createExpressionStatement(
                            factory.createBinaryExpression(
                              factory.createIdentifier("value"),
                              factory.createToken(ts.SyntaxKind.PlusEqualsToken),
                              factory.createBinaryExpression(
                                factory.createBinaryExpression(
                                  factory.createIdentifier("i"),
                                  factory.createToken(ts.SyntaxKind.PlusToken),
                                  factory.createIdentifier("index")
                                ),
                                factory.createToken(ts.SyntaxKind.PlusToken),
                                factory.createElementAccessExpression(
                                  factory.createIdentifier("arr"),
                                  factory.createIdentifier("index")
                                )
                              )
                            )
                          ),
                          factory.createReturnStatement(
                            factory.createCallExpression(
                              factory.createIdentifier("map"),
                              undefined,
                              [
                                factory.createArrayLiteralExpression(
                                  [
                                    factory.createNumericLiteral("1"),
                                    factory.createNumericLiteral("2"),
                                    factory.createNumericLiteral("3"),
                                    factory.createNumericLiteral("4"),
                                    factory.createNumericLiteral("5"),
                                  ],
                                  false
                                ),
                                factory.createFunctionExpression(
                                  undefined,
                                  undefined,
                                  undefined,
                                  undefined,
                                  [
                                    factory.createParameterDeclaration(
                                      undefined,
                                      undefined,
                                      undefined,
                                      factory.createIdentifier("i"),
                                      undefined,
                                      undefined,
                                      undefined
                                    ),
                                    factory.createParameterDeclaration(
                                      undefined,
                                      undefined,
                                      undefined,
                                      factory.createIdentifier("index"),
                                      undefined,
                                      undefined,
                                      undefined
                                    ),
                                    factory.createParameterDeclaration(
                                      undefined,
                                      undefined,
                                      undefined,
                                      factory.createIdentifier("arr"),
                                      undefined,
                                      undefined,
                                      undefined
                                    ),
                                  ],
                                  undefined,
                                  factory.createBlock(
                                    [
                                      factory.createExpressionStatement(
                                        factory.createBinaryExpression(
                                          factory.createIdentifier("value"),
                                          factory.createToken(ts.SyntaxKind.PlusEqualsToken),
                                          factory.createBinaryExpression(
                                            factory.createBinaryExpression(
                                              factory.createIdentifier("i"),
                                              factory.createToken(ts.SyntaxKind.PlusToken),
                                              factory.createIdentifier("index")
                                            ),
                                            factory.createToken(ts.SyntaxKind.PlusToken),
                                            factory.createElementAccessExpression(
                                              factory.createIdentifier("arr"),
                                              factory.createIdentifier("index")
                                            )
                                          )
                                        )
                                      ),
                                      factory.createExpressionStatement(
                                        factory.createPostfixUnaryExpression(
                                          factory.createIdentifier("value2"),
                                          ts.SyntaxKind.PlusPlusToken
                                        )
                                      ),
                                      factory.createReturnStatement(
                                        factory.createBinaryExpression(
                                          factory.createBinaryExpression(
                                            factory.createBinaryExpression(
                                              factory.createIdentifier("i"),
                                              factory.createToken(ts.SyntaxKind.PlusToken),
                                              factory.createIdentifier("index")
                                            ),
                                            factory.createToken(ts.SyntaxKind.PlusToken),
                                            factory.createElementAccessExpression(
                                              factory.createIdentifier("arr"),
                                              factory.createIdentifier("index")
                                            )
                                          ),
                                          factory.createToken(ts.SyntaxKind.PlusToken),
                                          factory.createIdentifier("value2")
                                        )
                                      ),
                                    ],
                                    true
                                  )
                                ),
                              ]
                            )
                          ),
                        ],
                        true
                      )
                    ),
                  ])
                ),
              ],
              ts.NodeFlags.Const
            )
          ),
          factory.createReturnStatement(
            factory.createArrayLiteralExpression(
              [
                factory.createIdentifier("value"),
                factory.createIdentifier("result"),
                factory.createIdentifier("target"),
              ],
              false
            )
          ),
        ],
        true
      )
    ),
  ],
  factory.createToken(ts.SyntaxKind.EndOfFileToken),
  ts.NodeFlags.Namespace
);
