# .github/workflows/main.yml
name: Rush Install

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Subtree deploy
        uses: nxtlvlsoftware/git-subtree-action@1.1
        with:
          repo: "yuyi919/shared"
          path: "packages/libs/shared"
          deploy_key: ${{ secrets.DEVELOP_SHARED }}
          force: true # will force push to the downstream repository
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
