# .github/workflows/main.yml
name: Rush Install

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Subtree ${{ secrets.SHARED_GITHUB_DEPLOY_KEY }}
        uses: xedi/action-subtree-sync@1.0.0
        with:
          subtree: "yuyi919/shared-packages"
          subtree_deploy_key: ${{ secrets.SHARED_GITHUB_DEPLOY_KEY }}
          split_prefix: "packages/libs/shared"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
